apiVersion: v1
kind: Service
metadata:
  name: flight-ops-service
  namespace: anadolu-flight-system
  labels:
    app.kubernetes.io/name: flight-ops-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: anadolu-flight-system
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8082"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: flight-ops-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
