apiVersion: 1

# Prometheus alertlerini Grafana'da göster
contactPoints:
  - orgId: 1
    name: default-email
    receivers:
      - uid: default-email
        type: email
        settings:
          addresses: admin@example.com
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: default-email
    group_by: ['grafana_folder', 'alertname']
